apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-deply
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comments
  template:
    metadata:
      labels:
        app: comments
    spec:
      containers:
        - name: comments
          image: cakitomakito/comments
          ports:
            - containerPort: 4001
